### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by OliverWarrington** [nvim-telescope/telescope-bibtex.nvim#10] opened 2021-03-17 13:52 UTC
I'm having a few issues getting this plugin configured, any help would be much appreciated!

1. Nothing shows up even though I have set global_files to point at my .bib file.
2. Even in the same directory as my .bib file, nothing shows up in existing md files, but it does in new md files.
3. If I save, exit and re-enter `new.md`, it does not work anymore.
4. Inserted citations are in latex format despite setting `format = md`.

Here is my config:

```
 local actions = require('telescope.actions')
  
  require('telescope').setup{
      defaults = {
          file_ignore_patterns = {"build/.*"},
          mappings = {
              i = {
                  ["<C-q>"] = actions.send_to_qflist + actions.open_qflist
              },
          },
      },
      extensions = {
          bibtex = {
              depth = 1,
              format = 'md',
              global_files = {'/Users/OliverW/wiki/entorhinal_layers/reading/bibliography.bib' },
          },
          frecency = {
              show_scores = false,
              show_unindexed = true,
              workspaces = {
                  ["7t"]      = "/Users/OliverW/Nextcloud/7T_EC_layers",
                  ["Zet"]    = "/Users/OliverW/wiki"
              }
          }
      }
  }
 
  -- Extensions
  require('telescope').load_extension('frecency')
  require('telescope').load_extension('gh')
  require('telescope').load_extension('octo')
  require'telescope'.load_extension("cheat")
  require'telescope'.load_extension("project")
  require"telescope".load_extension("bibtex")
```

Excited to get this going, fits perfectly in my workflow!

**Comment by noahares** [comment] 2021-03-17 14:35
Hey, 
I tried reproducing your issues, but eveything works fine for me... Do you see the empty popup window when you call `Telescope bibtex` on an existing file or do you not see anything at all? How did you install the plugin?

**Comment by OliverWarrington** [comment] 2021-03-17 14:39
Hey @noahares, thanks for checking this out. I do see the empty popup window. I installed with [paq](https://github.com/savq/paq-nvim).

**Comment by noahares** [comment] 2021-03-17 14:56
It seems really weird to me that it works on newly created files, but not on existing ones. Even if the config for global files is wrong, you still should be able to see the bib file in the cwd. You can try putting a `print(vim.inspect(result))` below line 95 to see whether any entries are extracted from to file. Or `print(vim.inspect(user_files)` after line 149 to see if the options arrive at the plugin. Sorry that I cannot help you further but I cannot pin down what might be the issue.

**Comment by OliverWarrington** [comment] 2021-03-17 15:09
`print(vim.inspect(result))` printed out the 2 entries I have in the bib file atm. But again only in a new file and only when the bib is in the cwd. `print(vim.inspect(user_files)` doesn't seem to print anything even when it works. I've double checked and the filetype is always the same in new and existing files in case that would make a difference. This definitely seems like a tricky one to pin down!

**Comment by noahares** [comment] 2021-03-17 15:21
Hmm, I think @jghauser had a similar problem once. He said it had something to do with incompatible settings? Maybe he has figured out what it was and can share some insights. 

Otherwise I see limited things I can do to help you with this :(

**Comment by jghauser** [comment] 2021-03-17 18:28
I've had some odd issues with seeing only an empty popup recently. I haven't been able to determine what exactly the problem was and it seems to have gone away now. Are you sure you're fully updated?

With regard to the config conflict, I'm unfortunately not sure anymore what exactly the problem was. I think it had something to do with where I loaded the bibtex extension (`require('telescope').load_extension('bibtex')`) and where I loaded my telescope config. Does it start working when you do `:lua require('plugins.telescope')` (adjust as necessary)? Try also manually loading the bibtex extension in this way. If this gets it working, you might indeed have run into the same problem as me, and I'll try to figure out what exactly it was that I did to solve it.

**Comment by OliverWarrington** [comment] 2021-03-17 19:01
Appreciate your input @jghauser! Unfortunately, no luck with changing the way I load the extension. 

I've had a dig around and noticed that my config is not actually getting read. So if I set depth to 10 for example, the code below, with my added print statement on line 152, always shows 1. Perhaps I put the print in the wrong place (not strong with lua) but maybe that helps @noahares?

```
139 return telescope.register_extension {
140   setup = function(ext_config)
141     depth = ext_config.depth or depth
142     local custom_formats = ext_config.custom_formats or {}
143     for _, format in pairs(custom_formats) do
144       formats[format.id] = format.cite_marker
145     end
146     user_format = ext_config.format or fallback_format
147     if formats[user_format] == nil then
148       user_format = fallback_format
149     end
150     user_files = ext_config.global_files or {}
151   end,
152    print("Here: ", vim.inspect(depth)),
153   exports = {
154     bibtex = bibtex_picker
155   },
156 }
```

**Comment by jghauser** [comment] 2021-03-18 04:13
Yeah, I had the same issue with it not getting read, but in my case I was able to 'manually' load my telescope config file by doing `:lua require('plugins.telescope')` in vim command mode. I later figured out that I had something not set up correctly in packer, though I don't remember precisely what that was. In any case, packer probably does things slightly differently than paq here. Sorry not to be able to be of more help :/

**Comment by jghauser** [comment] 2021-03-26 06:34
Ok, I've had this issue (bibtex extension settings not taking effect) reappear for me and seem to found a way of solving it. After looking at @noahares dotfiles, I noticed that he lazy-loads the extension for markdown and tex filetypes. I adjusted my packer config accordingly:

```lua
  -- telescope bibtex
  use {
    'nvim-telescope/telescope-bibtex.nvim',
    ft = {'tex', 'markdown'},
    branch = 'search_everything',
    config = function()
      require('telescope').load_extension('bibtex')
    end
  }
```

It works now. If I remove `ft = {'tex', 'markdown'}`, it stops working. Any idea why that might be the case? It does seem like unintended behaviour...

**Comment by noahares** [comment] 2021-03-26 09:33
I think it might stop working, because if you remove `ft`, the plugin gets loaded before the options are set in the telescope config table. But I am not sure about that. 

I checked the other telescope extensions, whether they do something different in their `load_extension` method, but I did not find anything. Maybe check if the behavior is the same in other telescope extensions.

**Comment by jghauser** [comment] 2021-03-26 11:00
> I think it might stop working, because if you remove ft, the plugin gets loaded before the options are set in the telescope config table. But I am not sure about that.

I think you're exactly right. I've added `after = 'telescope.nvim'` to my packer plugin config, and it works.

I've just tried it with the frecency extension (it's the only other extension that I use) and settings do seem to be picked up even without `ft` or `after`.

**Comment by noahares** [comment] 2021-03-26 11:13
Ok, nice. But that still leaves the question why it works with frecency. I double-checked their setup again and they do it no different, only a bit fancier for their defaults, if the user does not provide a value.

**Comment by jghauser** [comment] 2021-03-26 11:24
I have no idea. I'll play around with it when I get some time. Does the problem appear for you too when you comment out the `ft` line?

**Comment by noahares** [comment] 2021-03-26 11:50
When I comment out the ft, it still works for me. But only, if I install from github. Otherwise I get a packer error on `:PackerCompile` (I guess something to do with the rtp).

**Comment by adrianocorrea** [comment] 2022-07-14 11:30
I believe this issue is almost closed now. However,  I would like to share a setup that worked for me and makes the `init.lua` (or `init.vim`) portable between different operating systems (i.e. you can use the same settings on Windows, Linux and macOS). 

Here is the code

```lua
local telescope_bibfile = vim.fn.expand("~/reading/bibliography.bib")

require("telescope").setup({
   extensions = {
      bibtex = {
         global_files = { telescope_bibfile },
      },
   },
})

require("telescope").load_extension("bibtex")
```

Using `vim.fn.expand()` prevents the path errors that some people face when following the setup instructions while using an OS different from the one used to create the documentation. For example, it allows the users to set the `.bib` file as `~/reading/bibliography.bib`, as `/Users/myuser/reading/bibliography.bib` or as `C:\\Users\\myuser\\reading\\bibliography.bib`. By preventing these errors, one avoids the empty prompt.

**Comment by noahares** [comment] 2022-07-26 08:16
Thanks for the info. Would using `vim.fn.expand` internally on the provided path solve the issue for users with non-Unix OSes? I do not have a Windows system to test this.

**Comment by adrianocorrea** [comment] 2022-07-26 18:38
It would, @noahares. 

It also makes the `telescope-bibtex.vim`'s settings cross-platform, allowing users to use the same `.vimrc` (or `init.lua`) on Windows, macOS and Linux.

As a reference, all these alternatives will work on Windows:

* `C:\\my\\path\\bibliography.bib`
* `D:\\my\\path\\bibliography.bib`
* `C:/my/path/bibliography.bib`
* `D:/my/path/bibliography.bib`
* `~/my/path/bibliography.bib`

What won't work is `/Users/myuser/bibliography.bib`.

**Comment by noahares** [comment] 2022-07-30 13:39
9bb88b3ca7c88d8d29e66e4656484eea1719a8ea should take care of this.
Thanks @adrianocorrea for the input.
I assume you mean that `/Users/myuser/...` won't work on Windows, but should work on maxOS?
I will close this issue for now.
Let me know if any problems persist.

**Closed by noahares** 2022-07-30 13:39 UTC
